name: 🌻 Deploy & Quality Assurance

on:
  push:
    branches:
   - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  
jobs: 
  deploy:
    name: 🌛 Deploy TO Github pages
    runs on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs: 
      page_url: ${{ steps.deployment.outputs.page_url }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
